### ISSUE TITLE
Processed full data?

### ISSUE THREAD

**Issue by kexinhuang12345** [dahjan/DMS_opt#1]
Hey,

Thanks for the very interesting study! I am wondering if you could provide some guidance on the organization of the data folder? 

Thanks

**Comment by masondm** [comment]
Hi Kexin,
 
Please refer to the tables in the supplementary file for the paper for a little bit more description. Briefly, mHER = combinatorial mutagenesis on Herceptin, H3 = CDRH3, _#_ = number of enrichment rounds in DMS which the library is designed from, _#Ag = number of enrichment rounds of the combinatorial mutagenesis library.

For example:
mHER_H3_1_1Ag.txt

mHER: combinatorial mutagenesis on herceptin
H3: CDRH3
1: Combinatorial mutagenesis library designed from the 1st round of DMS
1Ag: One round of antigen enrichment

Cheers,
Derek

**Comment by kexinhuang12345** [comment]
Thanks! Will take a closer look
